[package]
name = "bulwark-proto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tonic.workspace = true
tonic-prost.workspace = true
prost.workspace = true
serde.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
protox.workspace = true
prost.workspace = true
