[package]
name = "bulwark-net"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
windows-tun = []
wg-client = ["dep:boringtun", "dep:rand_core"]

[dependencies]
bulwark-proto = { path = "../bulwark-proto" }
bulwark-core = { path = "../bulwark-core" }

hudsucker.workspace = true
rustls.workspace = true
tokio-rustls.workspace = true
rcgen.workspace = true
ring.workspace = true

tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
bytes.workspace = true
futures-util.workspace = true
http = "1"
http-body-util = "0.1"

boringtun = { workspace = true, optional = true }
rand_core = { version = "0.6.4", features = ["getrandom"], optional = true }

[target.'cfg(windows)'.dependencies]
wintun = { workspace = true }
windows = { version = "0.60", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Cryptography",
    "Win32_System_Memory",
    "Win32_System_Threading",
] }

[target.'cfg(any(windows, target_os = "linux", target_os = "macos"))'.dependencies]
tokio-util = { workspace = true }
smoltcp = { workspace = true }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
tun-rs = { workspace = true }
libc = "0.2"

[target.'cfg(target_os = "android")'.dependencies]
jni = { workspace = true }
tun-rs = { workspace = true }
libc = "0.2"
smoltcp = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
