//! DEV-ONLY visual demo (NOT for production): runs the real `AlertRelay` +
//! `Review` gRPC services on `127.0.0.1:8443` over **plaintext** (no TLS) and
//! injects synthetic, fully-redacted guardian alerts on a loop. Point the Dioxus
//! parent console at it to watch alerts stream in and Approve / Keep-blocked them:
//!
//! ```text
//!   cargo run -p aegis-server --example dev_demo          # this server
//!   # then, in apps/parent (AEGIS_CLUSTER_ENDPOINT=http://127.0.0.1:8443):
//!   cargo run                                             # the parent GUI
//! ```
//!
//! Privacy: every injected alert carries ONLY the no-media fields the invariant
//! permits (a hash, a redacted context line) — never a thumbnail or message body.
//! The CSAM-category sample exists so you can SEE that approving it is refused
//! (CSAM is never allowlistable).

use std::time::Duration;

use aegis_proto::v1::alert_relay_server::AlertRelayServer;
use aegis_proto::v1::review_server::ReviewServer;
use aegis_proto::v1::{AlertEvent, AlertKind, Category, Evidence, Severity};

use aegis_server::relay::{AlertHub, ReviewService};
use aegis_server::service::AlertRelayService;

use tonic::transport::Server;

fn now_ms() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

/// A real PNG generated by ffmpeg (`testsrc`), embedded so the demo can show the
/// parent console rendering an actual blocked-image PREVIEW (non-CSAM only). In
/// the live proxy path this is replaced by the real blocked image bytes.
const SAMPLE_IMG: &[u8] = include_bytes!("sample_block.png");

/// Build the `n`-th synthetic alert, rotating through a few realistic templates.
/// Non-CSAM alerts carry a preview (image and/or the actual flagged text) so the
/// guardian console can show WHAT was blocked; the CSAM sample carries neither.
fn demo_alert(n: u64) -> AlertEvent {
    // (category, kind, app, context, flagged-text snippet, attach image preview?)
    let templates: &[(Category, AlertKind, &str, &str, &str, bool)] = &[
        (
            Category::AdultImage,
            AlertKind::Intervention,
            "example.com",
            "Adult image blocked on a web page",
            "",
            true,
        ),
        (
            Category::Grooming,
            AlertKind::GroomingSuspected,
            "messenger",
            "Possible grooming detected in a chat",
            "hey it's our little secret \u{2014} don't tell your mum \u{1f609} send me a pic, you can delete it after",
            false,
        ),
        (
            Category::AdultAudio,
            AlertKind::Intervention,
            "a-video-site",
            "Adult content muted in a video (frame preview)",
            "",
            true,
        ),
        (
            Category::CsamSuspected,
            AlertKind::Intervention,
            "unknown-host",
            "Suspected illegal content blocked",
            "",
            false,
        ),
    ];
    let (cat, kind, app, ctx, snippet, has_image) = templates[(n as usize) % templates.len()];
    let is_csam = matches!(cat, Category::CsamSuspected);

    // CSAM: never carry any preview. Non-CSAM: attach the sample image and/or the
    // flagged text so the parent console can show exactly what was blocked.
    let safe_thumbnail = if has_image && !is_csam {
        SAMPLE_IMG.to_vec()
    } else {
        Vec::new()
    };
    let text_snippet = if is_csam { String::new() } else { snippet.to_string() };

    AlertEvent {
        alert_id: format!("demo-{n}"),
        kind: kind as i32,
        category: cat as i32,
        severity: Severity::High as i32,
        app: app.to_string(),
        device_id: "kids-tablet".to_string(),
        ts: now_ms(),
        redacted_context: ctx.to_string(),
        evidence: Some(Evidence {
            sha256: vec![(n & 0xff) as u8, 0xde, 0xad, 0xbe, 0xef],
            perceptual_hash: Vec::new(),
            safe_thumbnail,
            text_snippet,
            model_id: "demo".to_string(),
            model_version: "0".to_string(),
        }),
        ..Default::default()
    }
}

#[tokio::main(flavor = "multi_thread", worker_threads = 2)]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let addr = "127.0.0.1:8443".parse()?;

    // One shared hub backs both services, exactly as an all-in-one node wires it.
    let hub = AlertHub::new();
    let relay = AlertRelayService::new(hub.clone(), None); // no SMTP sink in the demo
    let review = ReviewService::new(hub.clone());

    // Synthetic-alert injection is OPT-IN (set AEGIS_DEMO_INJECT=1). By default this
    // runs as a CLEAN relay: AlertRelay + Review only, so the parent console shows
    // ONLY real blocks (e.g. from aegis_proxy). With the env set, it emits a sample
    // alert every few seconds for a UI demo. publish() fans out + records the
    // alert's content-free facts so a later APPROVE/DENY can resolve it.
    if std::env::var("AEGIS_DEMO_INJECT").is_ok() {
        let inject_hub = hub.clone();
        tokio::spawn(async move {
            tokio::time::sleep(Duration::from_secs(2)).await;
            let mut n: u64 = 1;
            loop {
                let ev = demo_alert(n);
                let reached = inject_hub.publish(ev.clone());
                eprintln!(
                    "[demo] published {} (category={}) -> {reached} live guardian stream(s)",
                    ev.alert_id, ev.category
                );
                n += 1;
                tokio::time::sleep(Duration::from_secs(4)).await;
            }
        });
    } else {
        eprintln!("[demo] sample injection OFF (set AEGIS_DEMO_INJECT=1 to emit demo alerts);");
        eprintln!("[demo] running as a CLEAN relay — only real blocks will appear.");
    }

    eprintln!("[demo] AlertRelay + Review serving PLAINTEXT on http://{addr}");
    eprintln!("[demo] run the parent with AEGIS_CLUSTER_ENDPOINT=http://127.0.0.1:8443");
    eprintln!("[demo] Ctrl-C to stop.");

    Server::builder()
        .add_service(AlertRelayServer::new(relay))
        .add_service(ReviewServer::new(review))
        .serve(addr)
        .await?;

    Ok(())
}
