/*
 * SCAFFOLD — not built here.
 * See platform/rom/README.md for integration instructions.
 *
 * Licence: Apache-2.0
 * SPDX-License-Identifier: Apache-2.0
 *
 * ============================ SUPERSEDED ============================
 * As of PR #223 the Rust core in `libbulwark_safety/rust/` implements the
 * PUBLIC ABI (`include/bulwark_safety.h`) DIRECTLY — exporting
 * `bw_init_once`, `bw_score_nsfw`, `bw_score_text` AND `bw_model_id`. It is
 * the SOLE implementation of that ABI.
 *
 * DO NOT compile this .cpp into the same library as the Rust cdylib/staticlib:
 * both define `bw_init_once`/`bw_score_nsfw`/`bw_model_id`, so co-linking them
 * is a DUPLICATE-SYMBOL error. This file also predates `bw_score_text` (it has
 * no counterpart here) and calls `bw_rs_*` symbols the Rust core does not export.
 *
 * Integration (on the Linux/AOSP host): link the Rust staticlib
 * (`libbulwark_safety.a`) into `bulwarkd` and `libcameraservice` and DELETE this
 * wrapper, OR — if a C++ shim is still wanted for the NV21/NV12→RGBA conversion —
 * rename its exports so they do not collide with the ABI and have it forward to
 * the Rust symbols. Kept only as a reference for the YUV-conversion shim until
 * that wiring lands. See `docs/design/child-safety-rom-build.md` §5.1.
 * ===================================================================
 *
 * bulwark_safety.cpp — thin C++ wrapper over the Rust bulwark-vision FFI.
 *
 * This file provides the implementation of the public C API declared in
 * include/bulwark_safety.h. It delegates all actual inference to the Rust
 * cdylib (libbulwark_safety_rs), which bundles the ORT session, the baked
 * ONNX model, and the pre/post-processing pipeline from crates/bulwark-vision.
 *
 * The C++ layer exists because:
 *   1. libcameraservice is C++; linking a Rust cdylib directly into it would
 *      require Rust toolchain in the AOSP build graph (not yet standard).
 *   2. The format-conversion shim (NV21/NV12 → RGBA) is simpler in C++ with
 *      Android's existing color-conversion utilities (libyuv, already in AOSP).
 *   3. A stable C ABI (extern "C") insulates libcameraservice from Rust ABI
 *      changes.
 *
 * === FFI bridge (TODO on Linux host) ===
 *
 * The Rust cdylib must expose the following extern "C" symbols, which are
 * declared in include/bulwark_safety_ffi.h (generated by cbindgen from
 * crates/bulwark-vision):
 *
 *   int bw_rs_init(const char* model_path_or_null);
 *   int bw_rs_score_rgba(
 *       const uint8_t* rgba, int w, int h, float* score_out);
 *   const char* bw_rs_model_id(void);
 *
 * To generate:
 *   cd crates/bulwark-vision
 *   cbindgen --config cbindgen.toml --output ../../platform/rom/libbulwark_safety/include/bulwark_safety_ffi.h
 *
 * Then build the cdylib for arm64-v8a:
 *   cargo ndk -t arm64-v8a -o ../../platform/rom/libbulwark_safety/prebuilt build \
 *       --release -p bulwark-vision-ffi
 *
 * A Cargo.toml entry for the FFI shim crate is needed in crates/bulwark-vision-ffi/
 * (does not exist yet — TODO). It should re-export the VisionAnalyzer scorer
 * through the C ABI defined above.
 *
 * === Colour-conversion note ===
 *
 * Camera3OutputStream gralloc buffers are typically HAL_PIXEL_FORMAT_YCbCr_420_888
 * (NV21 or NV12 plane layout) for preview/video and HAL_PIXEL_FORMAT_JPEG or
 * HAL_PIXEL_FORMAT_RGBA_8888 for still captures. This wrapper converts NV21/NV12
 * to RGBA via libyuv (already in AOSP) before passing to the Rust scorer, which
 * expects RGBA (mirrors NsfwGate.kt's Bitmap.getPixels() → ARGB8888 path).
 *
 * TODO: confirm the exact gralloc format used by Camera3OutputStream on
 * android-16.0.0_r3 + lynx vendor HAL before finalising the conversion path.
 */

// SCAFFOLD — body is intentionally skeletal. Real implementation is TODO
// on the Linux build host once the Rust FFI crate (bulwark-vision-ffi) exists.

#include "bulwark_safety.h"

// TODO: replace with the cbindgen-generated header once bulwark-vision-ffi exists.
// #include "bulwark_safety_ffi.h"

// AOSP system libraries available to libcameraservice.
#include <android/log.h>
#include <stdatomic.h>
#include <string.h>

// libyuv (AOSP) — NV21/NV12 → RGBA conversion.
// TODO: add libyuv to shared_libs in Android.bp before building.
// #include <libyuv.h>

#define LOG_TAG "libbulwark_safety"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,  LOG_TAG, __VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN,  LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

// ---- internal state --------------------------------------------------------

/** 0 = not initialised, 1 = initialised OK, 2 = init failed (no model). */
static _Atomic int g_init_state = 0;

// ---- public API ------------------------------------------------------------

extern "C" int bw_init_once(const char* model_path) {
    // Idempotent — second call from any thread returns immediately.
    int expected = 0;
    if (!atomic_compare_exchange_strong(&g_init_state, &expected, -1 /*sentinel*/)) {
        // Another thread already ran init (or is running it now).
        while (atomic_load(&g_init_state) == -1) {
            // Spin-wait for the initialising thread to finish.
            // In practice the model load takes ~100–500 ms; this will not loop long.
        }
        int state = atomic_load(&g_init_state);
        return (state == 1) ? BW_ALREADY_INIT : BW_ERR_NO_MODEL;
    }

    // TODO: call the Rust cdylib once bulwark-vision-ffi exists:
    //   int rc = bw_rs_init(model_path);
    //   if (rc != 0) {
    //       LOGW("NSFW model could not be loaded (rc=%d); fail-CLOSED mode", rc);
    //       atomic_store(&g_init_state, 2);
    //       return BW_ERR_NO_MODEL;
    //   }
    //   LOGI("NSFW model loaded (%s)", bw_rs_model_id());
    //   atomic_store(&g_init_state, 1);
    //   return BW_OK;

    // SCAFFOLD stub: pretend no model is available so that any build-time
    // linkage test of this skeleton immediately enters fail-CLOSED mode rather
    // than silently passing frames through.
    (void)model_path;
    LOGW("bw_init_once: SCAFFOLD stub — no real model loaded; fail-CLOSED");
    atomic_store(&g_init_state, 2 /* no model */);
    return BW_ERR_NO_MODEL;
}

extern "C" BwVerdict bw_score_nsfw(
        const uint8_t* pixels,
        int            width,
        int            height,
        BwPixelFormat  fmt,
        float*         score_out) {

    // Validate inputs — fail-CLOSED on any bad argument.
    if (pixels == nullptr || width < 1 || height < 1) {
        LOGW("bw_score_nsfw: invalid input (pixels=%p w=%d h=%d); fail-CLOSED",
             pixels, width, height);
        return BW_VERDICT_FAIL_CLOSED;
    }

    // If model failed to load, fail-CLOSED immediately.
    if (atomic_load(&g_init_state) != 1) {
        return BW_VERDICT_FAIL_CLOSED;
    }

    // Convert NV21/NV12 → RGBA before passing to the Rust scorer.
    // The Rust scorer expects RGBA8888 (mirrors NsfwGate.kt's getPixels() path).
    const uint8_t* rgba_pixels = pixels;
    uint8_t* conversion_buf = nullptr;

    if (fmt == BW_FMT_NV21 || fmt == BW_FMT_NV12) {
        // TODO: use libyuv for the conversion once Android.bp adds it.
        // Allocate a temporary RGBA buffer (width * height * 4 bytes).
        //   conversion_buf = new uint8_t[width * height * 4];
        //   if (fmt == BW_FMT_NV21) {
        //       libyuv::NV21ToARGB(pixels, width,
        //                          pixels + width * height, width,
        //                          conversion_buf, width * 4,
        //                          width, height);
        //   } else { /* NV12 */
        //       libyuv::NV12ToARGB(pixels, width,
        //                          pixels + width * height, width,
        //                          conversion_buf, width * 4,
        //                          width, height);
        //   }
        //   rgba_pixels = conversion_buf;
        LOGW("bw_score_nsfw: YUV conversion not yet wired (TODO libyuv); fail-CLOSED");
        return BW_VERDICT_FAIL_CLOSED;
    }

    // TODO: call the Rust cdylib once bulwark-vision-ffi exists:
    //   float score = 0.0f;
    //   int rc = bw_rs_score_rgba(rgba_pixels, width, height, &score);
    //   delete[] conversion_buf;
    //   if (rc != 0) {
    //       return BW_VERDICT_FAIL_CLOSED;
    //   }
    //   if (score_out != nullptr) *score_out = score;
    //   return (score >= 0.7f) ? BW_VERDICT_NSFW : BW_VERDICT_SAFE;

    // SCAFFOLD stub: always fail-CLOSED so no real frames are passed through.
    (void)rgba_pixels;
    (void)score_out;
    delete[] conversion_buf;
    return BW_VERDICT_FAIL_CLOSED;
}

extern "C" const char* bw_model_id(void) {
    // TODO: return bw_rs_model_id() once the Rust cdylib is wired.
    int state = atomic_load(&g_init_state);
    if (state == 0)  return "not-initialised";
    if (state == 2)  return "stub-noop";
    // TODO: return bw_rs_model_id();
    return "stub-noop"; // SCAFFOLD placeholder
}
