[package]
name = "aegis-policy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aegis-proto = { path = "../aegis-proto" }
serde.workspace = true
figment.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
